# User Profile: VOSS, K.
# Employee ID: KV-7031
# Clearance: Level 4
# Department: Special Projects -- Project LETHE
# Terminal: NX7-031
#
# NOTE: This profile was auto-generated by Omnicron HR.
# Do not modify without IT approval.

export USER="kai.voss"
export HOME="/local"
export OMNICRON_EMP_ID="KV-7031"
export CLEARANCE_LEVEL=4
export FACILITY="NEXUS-7"
export FLOOR=7
export DEPARTMENT="SPECIAL_PROJECTS"
